import Article from '@/components/Article'
import { getAllArticles } from 'lib'
import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'

// this page will list all the articles that can be clicked
// it needs information about all the pages then
// get all the posts on the server and dump on the frontend

const Home = (props: {
  articles: {
    content: string
    data: {
      title: string
      excerpt: string
      tags: string[]
      date: string
      slug: string
    }
  }[]
}) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        style={{
          marginInline: '20rem',
          marginBlockStart: '4rem',
        }}
      >
        <h1>Articles</h1>
        {props.articles.map((article) => (
          <Article {...article} />
        ))}
      </main>
    </div>
  )
}

export default Home

// Amean, we can pass the markdown files directly but we have no idea how to render them
// Another option will probably be to use json files and render them as HTML
export async function getStaticProps() {
  const articles = getAllArticles()

  return {
    props: {
      articles,
    },
  }
}
